openapi: 3.1.0
info:
  title: Personality Time API
  version: 1.0.0
servers:
  - url: https://personality-judge-api.onrender.com
paths:
  /time:
    get:
      operationId: getTime  # ← これが重要
      summary: 現在の秒数を返すAPI
      responses:
        '200':
          description: 秒数のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  second:
                    type: integer
                    description: 現在の秒数（0〜59）
